Repository ProofGeneral/PG, pull requests merged in 2020-05, with the labels that each got.

#488 doc/ProofGeneral.texi: fix makeinfo
  .github/workflows/test.yml
  doc/ProofGeneral.texi
Labels: kind: documentation, kind: fix

#496 fix: test files should not provide features
  coq/coq-par-test.el
  etc/testsuite/pg-pgip-test.el
  etc/testsuite/pg-test.el
Labels: kind: cleanup, kind: test

#490 Improve PG support of Show Proof Diffs
  ci/coq-tests.el
  coq/coq-abbrev.el
  coq/coq-compile-common.el
  coq/coq-syntax.el
  coq/coq.el
  generic/proof-config.el
  generic/proof-shell.el
Labels: kind: feature
