Repository ProofGeneral/PG, pull requests merged in 2020-04, with the labels that each got.

#474 Add support for core Ltac2 syntax
  coq/coq-syntax.el
Labels: kind: enhancement

#476 Fix documentation about Coq electric terminator
  doc/ProofGeneral.texi
Labels: kind: documentation, kind: fix

#480 feat(coq-insert-intros): Conditionally insert `move=>` or `intros`
  coq/coq.el
Labels: kind: feature

#435 Correctly run coqidetop
  HOWTO-USE
  coq/coq-local-vars.el
  coq/coq-system.el
Labels: pg: async

#483 Use GitHub actions
  .github/workflows/test.yml
  .travis.yml
  Makefile.travis
  README.md
  ci/coq-tests.el
  ci/init-tests.el
  ci/test.sh
Labels: kind: infrastructure, kind: test
