Repository ProofGeneral/PG, pull requests merged in 2021-09, with the labels that each got.

#593 Minor tweaks encountered while trying to run the CI tests
  .github/workflows/test.yml
  .gitignore
  Makefile
  ci/coq-tests.el
Labels: kind: test

#598 fix #596 - outdated documentation for setup coq-prog-xxx.
  doc/ProofGeneral.texi
Labels: kind: documentation, kind: cleanup

#601 fix: parsing of `coqtop -v` for 8.14+rc1
  coq/coq-system.el
Labels: kind: fix
