Repository ProofGeneral/PG, pull requests merged in 2022-11, with the labels that each got.

#676 docs(README.md): Update badges
  README.md
Labels: kind: documentation

#675 Miscellaneous improvements of qrhl-tool support
  qrhl/qrhl-input.el
  qrhl/qrhl.el
Labels: kind: enhancement

#669 Do not offer to save (temporary) buffers without associated files
  generic/proof-script.el
Labels: kind: fix
