Repository ProofGeneral/PG, pull requests merged in 2022-02, with the labels that each got.

#638 Fix version number parsing on some confused Windows installations
  coq/coq-system.el
Labels: kind: fix

#630 docs: Update README.md
  README.md
Labels: kind: documentation

#636 Support for qrhl-tool theorem prover
  Makefile.devel
  README.md
  doc/PG-adapting.texi
  doc/ProofGeneral.texi
  generic/proof-autoloads.el
  generic/proof-site.el
  qrhl/qrhl-input-25.el
  qrhl/qrhl-input.el
  qrhl/qrhl.el
Labels: kind: feature
