Repository ProofGeneral/PG, pull requests merged in 2023-03, with the labels that each got.

#680 Add Coq tactic "native_compute".
  coq/coq-syntax.el
Labels: kind: enhancement

#692 coq-syntax.el: Fix state-changing booleans for commands
  coq/coq-syntax.el
Labels: kind: fix

#693 coq/coq.el: add a tiny bit of documentation
  coq/coq.el
Labels: kind: documentation
